---
title: "simpleRegress"
author: "Colton Beardsley"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

## Model LENGTH ~ NECK  this is an example  


```{r}
print("First")
HeadLen <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(HeadLen)
summary.lm(HeadLen)
```

```{r}
print("Second")
Chest <- lm(LENGTH~CHEST,data=bears)
plot(LENGTH~CHEST,data=bears)
abline(Chest)
summary.lm(Chest)
```

```{r}
print("Third")
Neck <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(Neck)
summary.lm(Neck)
```

```{r}
print("Fourth")
Weight <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(Weight)
summary.lm(Weight)
```

```{r}
print("Fifth")
HeadWth <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(HeadWth)
summary.lm(HeadWth)
```


## Compare all models that predict LENGTH other than NECK. Then order them from worst to best by its value of Adjusted-Rsquared (bigger is better), or by RSE (residual standard error) where smaller is better. 

